apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-spring-boot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/my-org/my-k8s-configs.git'
    path: 'k8s'
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
